liip_imagine:
    driver: gd
    resolvers:
        profile:
            web_path:
                web_root: %kernel.root_dir%/../web/
                cache_prefix: %liip_imagine_path.cache_prefix%
    loaders:
        profile_loader:
            filesystem:
                data_root: %kernel.root_dir%/..%liip_imagine_path.data_root%
    cache: profile
    filter_sets:
        filter_211x285:
            data_loader: profile_loader
            quality: 80
            filters:
                thumbnail: { size: [211, 285], mode: outbound }